//Array of products objects that include all informations

let products = [
  {
    type: "product",
    id: "0001",
    brand: "Audemars Piguet",
    name: "Royal OAK",
    price: "14.050€",
    image: "./assets/ap.avif",
  },
  {
    type: "product",
    id: "0002",
    brand: "Hublot",
    name: "Classic Fusion",
    price: "13.000€",
    image: "./assets/hublot.jpg",
  },
  {
    type: "product",
    id: "0003",
    brand: "Rolex",
    name: "Date Just",
    price: "9.550€",
    image: "./assets/rolex.avif",
  },
  {
    type: "product",
    id: "0004",
    brand: "Omega",
    name: "Seamaster",
    price: "7.300€",
    image: "./assets/omega.webp",
  },
  {
    type: "product",
    id: "0005",
    brand: "Tag Heuer",
    name: "Carrera",
    price: "5.850€",
    image: "./assets/tag.webp",
  },
  {
    type: "product",
    id: "0006",
    brand: "Patek Philippe",
    name: "Nautilus",
    price: "30.500€",
    image: "./assets/patek.jpg",
  },
  {
    type: "product",
    id: "0007",
    brand: "Rolex",
    name: "Navitimer",
    price: "8.450€",
    image: "./assets/breitling.jpg",
  },
  {
    type: "product",
    id: "0008",
    brand: "Cartier",
    name: "Santos",
    price: "12.800€",
    image: "./assets/cartier.webp",
  },
  {
    type: "product",
    id: "0009",
    brand: "IWC",
    name: "Portugieser",
    price: "10.600€",
    image: "./assets/IWC.jpg",
  },
  {
    type: "product",
    id: "0010",
    brand: "Richard Mille",
    name: "RM 011",
    price: "150.000€",
    image: "./assets/rm_011.jpg",
  },
];

export default products;
